# Site settings
title: Dave's Blog
description: A simple blog powered by Jekyll and GitHub Pages
author: Dave

# Build settings
markdown: kramdown
theme: minima

# Permalinks
permalink: /posts/:title/